.\" Version: 0.180.0
.\"
.TH SAPHanaSR-manageAttr 8 "14 Apr 2021" "" "SAPHanaSR-ScaleOut"
.\"
.SH NAME
SAPHanaSR-manageAttr \- Helps with managing Linux cluster attributes for SAP HANA system replication.
.\"
.SH SYNOPSYS
\fBSAPHanaSR-manageAttr\fR [ --help | --version ]
.br
\fBSAPHanaSR-manageAttr\fR --sid=\fISID\fR --ino=\fIINSTNO\fR --case \fIusecase\fR [ --check | --migrate \fIresource\fR ]
.\"
.SH DESCRIPTION
SAPHanaSR-manageAttr \- Helps with managing Linux cluster attributes for SAP HANA system replication.
.\" TODO more description
.\"
.SH OPTIONS
.TP 4
\fB --help\fR | \fB-h\fR
show help
.TP 4
\fB --version\fR | \fB-v\fR
show script version
.TP 4
\fB --check\fR | \fB-c\fR
check, if all recommended pre-requisites for a migration are met
.TP 4
\fB --migrate\fR | \fB-m\fR \fIresource\fR
migrate that given resource, relatd to the use case
.TP 4
\fB --case\fR | \fB-u\fR \fIusecase\fR
migration use case to process, currently only "multi-target"
.\" TODO what use cases? 
.TP 4
\fB --sid=\fISID\fR
use SID of the SAP system
.TP 4
\fB --ino=\fIINSTNO\fR
use instance number of the SAP system
.\"
.SH SUPPORTED PARAMETERS
.TP
\fBhana_${sid}_gra\fR = [ \fIgeneration\fR ]
The resource agent (RA) generation attribute identifies which generation of the RA is running. It helps determing RA's capabilities and performing cluster-wide upgrades of RA and srHook. The generation should be same for both on all nodes of the Linux cluster after successful upgrade. See also hana_${sid}_gsh.
.TP
\fBhana_${sid}_gsh\fR = [ \fIgeneration\fR ]
The srHook generation attribute identifies which generation of the srHook is running. It helps determing srHook's capabilities and performing cluster-wide upgrades of RA and srHook. E.g. starting with generation 2.0 the RA supports scale-out multi-target system replication, which needs replacement of the old SAPHanaSR.py by new SAPHanaSrMultiTarget.py. See also hana_${sid}_gra.
.TP
\fBhana_${sid}_site_srHook_${SITE}\fR = [ SOK | SFAIL | SWAIT | SREG | PRIM ]
The SAPHanaController and SAPHana RA recognize the effecting system replication status via srHook attributes in the CIB properties section. The scale-out multi-target aware attribute is site-specific. This attribute is used after sucessful migration or fresh installation into target state. See also SAPHanaSrMultiTarget.py(7). The SAP System Indentifier (sid) is given in lower case.
.TP
\fBhana_${sid}_glob_srHook\fR = [ SOK | SFAIL | SWAIT | SREG | PRIM ]
The old-style srHook attributes in the CIB properties section does not contain site-specific information. This attribute is to be replaced by the migration. See also SAPHanaSR.py(7). The SAP System Indentifier (sid) is given in lower case.
.TP
\fBhana_${sid}_glob_mts\fR = [ true | false ]
The multi-target support attribute identifies whether the Linux cluster supports HANA scale-out multi-target system replication. The SAP System Indentifier (sid) is given in lower case.
.\" TODO See also
.TP
\fBhana_${sid}_glob_upd\fR = [ ok | nok ]
The update status attribute identifies whether the whole cluster has sucessfully passed an update procedure. The SAP System Indentifier (sid) is given in lower case.
.\" TODO See also
.\"
.SH RETURN CODES
.B 0
Successful program execution.
.br
.B >0
Usage, syntax or execution errors.
.\"TODO meaning of INFO WARNING ERROR
.\"
.SH EXAMPLES 
\fB*\fR Overview on upgrading old-style hook to multi-target hook.

Upgrade procedure from defined entry state with old-style hook into defined
target state with multi-target enabled hook. This case is the main target for
the upgrade.
Certain steps are described in more detail as separate examples. Also see
REQUIREMENTS section below for defined states. The procedure at a glance:
.RS 4
1. Install scale-out multi-target aware SAPHanaSR-ScaleOut package on all nodes.
.br 
2. Check Linux cluster for matching defined migration entry state.
.br
3. Check HANA HADR provider configuration and related script on both sites.
.br
4. Set SAPHanaController m/s resource into maintenance.
.br
5. Replace HANA HADR provider configuration on both sites and reload hook.
.br
6. Check HANA HADR provider configuration and related script on both sites.
.br
7. Migrate srHook attribute from old-style to multi-target.
.br
8. Check Linux cluster for matching defined migration target state.
.br
9. Set SAPHanaController m/s resource from maintenance back into managed.
.br
10. Finally check if everything looks fine.
.br
11. Optionally connect third HANA site via system-replication outside of the Linux cluster.
.RE

As final result of this upgrade, the RAs and hook script are updated from
old-style to multi-target. Further the Linux cluster's srHook attribute is
migrated and new auxiliary attributes are introduced. 
.\" TODO what attributes

\fB*\fR Overview on upgrading existing multi-target hook to new one. 

Upgrade procedure from defined entry state already using a specific
multi-target enabled hook into defined target state with productional
multi-target enabled hook.
This case is relevant for early adopters who attended the ramp-up phase.
Certain steps are described in more detail as separate examples. Also see
REQUIREMENTS section below for defined states. The procedure at a glance:
.RS 4
1. Install scale-out multi-target aware SAPHanaSR-ScaleOut package on all nodes.
.br
2. Check Linux cluster for matching defined migration entry state.
.br
3. Reload hook on both sites.
.br
4. Check Linux cluster for matching defined migration target state.
.RE

As final result of this upgrade, the already multi-target aware RAs and hook
script are updated to an new version. Further new auxiliary attributes are
introduced.
.\" TODO what attributes

\fB*\fR Overview on upgrading old-style hook to new one, no multi-target hook.

Upgrade procedure from defined entry state with old-style hook into defined
target state with old-style hook.
This case is relevant for customer who do not want to change from old-style to
multi-target, but just upgrade the RPM. Certain steps are described in more
detail as separate examples. Also see REQUIREMENTS section below for defined
states. The procedure at a glance:
.RS 4
1. Install scale-out multi-target aware SAPHanaSR-ScaleOut package on all nodes.
.br
2. Reload hook on both sites.
.br
3. Check Linux cluster for matching defined migration target state.
.RE

As final result of this upgrade, the RAs and hook script are updated to an new
version. Further new auxiliary attributes are introduced.

\fB*\fR Check Linux cluster for matching defined migration entry state.

This should be always the first step during migration procedure. The check shows if all nodes are online, no resource failures are recorded, HANA is healthy and system replication is in sync. The whole Linux cluster is checked at once. Of course the same check is useful after the migration. See also SAPHanaSR_maintenance_examples(7). Example SID is ABR, instance number is 00.
.RS 4
# crm_mon -1r
.br
# SAPHanaSR-showAttr
.br
# cs_clusterstate -i
.br
# SAPHanaSR-manageAttr --sid=ABR --ino=00 --case multi-target --check
.RE
.\" TODO check details

\fB*\fR Remove logger information from script output.

This might be useful when capturing script output for documentation, or if screen width is limited otherwise. Example SID is ABR, instance number is 00.
.RS 4
# SAPHanaSR-manageAttr --sid=ABR --ino=00 --case multi-target --check 2>&1 | colrm 1 45
.RE

\fB*\fR Check HANA HADR provider configuration and related script.

This should the be second step during migration procedure. The check should be done at both sites. Of course the same check is useful after the migration. See also SAPHanaSrMultiTarget.py(7). Example SID is ABR, instance number is 00.
.\" TODO is this done by the SAPHanaSR-manageAttr?

\fB*\fR Replace HANA HADR provider configuration

The Linux cluster and HANA have to be checked for matching the entry state prior to replacing the HANA HADR provider configuration. This task needs to be done at both sites. See example above and REQUIREMENTS section below. Example SID is ABR. 
.\" TODO Replace HANA HADR provider configuration
.\" TODO describe sr_takeover?

\fB*\fR Reload HANA HADR provider hook script from persistence into running HANA

When installing an new package version, the HANA HADR provider hook script might
be updated on-disk. Nevertheless HANA is still running with the old version of
that script. To make changes active, the new script can be loaded from disk into
HANA. This should be done on both sites. Please refer to SAP documentation for
details. Example lowercase-SID (sid) is abr.
.RS 4
# su - ha1adm
.br
~> hdbnsutil -reloadHADRProviders; echo $?
.br
~> cdtrace
.br
~> grep HADR.*SAPHanaS nameserver.*trc
.br
~> exit
.RE

\fB*\fR Migrate srHook attribute from old-style to multi-target 

The Linux cluster and HANA have to be checked for matching the entry state prior to migrating the srHook attribute. See example above and REQUIREMENTS section below. Example SID is ABR, lowercase-SID is abr, instance number is 00, SAPHanaController m/s resource is msl_SAPHanaCon_ABR00. 
.\" TODO SAPHanaSrMultiTarget.py in global.ini? re-load global.ini and hook online? 
.RS 4
# SAPHanaSR-showAttr
.br
# crm resource maintenance msl_SAPHanaCon_ABR00 on
.br
# SAPHanaSR-manageAttr --sid=ABR --ino=00 --case multi-target --migrate
.br
# crm_attribute -n hana_abr_glob_srHook -D -t crm_config
.br
# SAPHanaSR-showAttr
.RE

\fB*\fR Delete srHook generation (gsh) and RA generation (gra) from node.

Might be useful for repeating a migration test. Usually this is not needed. Example node is suse12, lowercase-SID (sid) is abr.
.RS 4
# SAPHanaSR-showAttr
.br
# crm_attribute --delete -t node -N suse12 -n hana_abr_gsh -l reboot
.br
# crm_attribute --delete -t node -N suse12 -n hana_abr_gra -l forever
.br
# SAPHanaSR-showAttr
.RE
.\"
.SH FILES
.TP 4
/usr/sbin/SAPHanaSR-manageAttr
the program itself
.TP 4
/usr/share/SAPHanaSR-ScaleOut/SAPHanaSR.py
the scale-out old-style hook provider, delivered with the RPM for backward compatibility
.TP 4
/usr/share/SAPHanaSR-ScaleOut/SAPHanaSrMultiTarget.py
the scale-out multi-target aware hook provider, delivered with the RPM
.TP 4
/hana/shared/$SID/global/hdb/custom/config/global.ini
the on-disk representation of HANA global system configuration
.TP 4
/dev/stderr
SAPHanaSR-manageAttr writes even regular output to stderr
.\"
.SH REQUIREMENTS
\fB*\fR For upgrading resource agents, hook script and related attributes, Linux cluster and HANA are in one of the defined migration entry states. Defined entry states are:
.PP
.RS 4 
1. The cluster is using old-style global srHook status attribute. All cluster nodes are online in the cluster and there are no current errors in the cluster or HANA. No third HANA site is attached. Main use case for SAPHanaSR-manageAttr.
.PP
2. The site-based srHook attributes are already in correct use, no old-style global attribute is in use. A third HANA site might be attached. Can be found at early adopters.
.PP
3. The cluster is set up from scratch. A third HANA site might be attached. There are neither old-style global, nor site-based srHook attributes.
.RE
.PP
\fB*\fR The SAPHanaController m/s resource needs to be set into maintenance mode during migration.
.PP
\fB*\fR The old-style global srHook status attribute will be deleted manually as part of the migration procedure.
.PP
\fB*\fR Both HANA sites need to re-load the global.ini and the HADR provider script. If that is achieved by re-starting HANA, an SR take-over might help reducing service impact. Please refer to SAPHanaSR_maintenance_examples(7) for how performing an SR take-over.
.PP
\fB*\fR The HANA config file global.ini is located at /hana/shared/$SID/global/hdb/custom/config/global.ini .
.PP
\fB*\fR The Linux cluster can be either upgraded to the defined migration target state, or run unchanged with the old-style global attribte and related hook script. Not allowed is mixing old and new attributes or hook scripts within one Linux cluster.
.PP
\fB*\fR See also the REQUIREMENTS section of SAPHanaSR-ScaleOut(7) and SAPHanaSrMultiTarget.py(7) for general requirements and for technical details.
.\"
.SH BUGS
Formatting  and  content of this script's output will change, since this script
is under development. This script is not intended  to  be  called from tools.
.br
In case of any problem, please use your favourite SAP support process to open
a request for the component BC-OP-LNX-SUSE. Please report any other feedback
and suggestions to feedback@suse.com.
.\"
.SH SEE ALSO
\fBocf_suse_SAPHanaController\fP(7) , \fBSAPHanaSR-ScaleOut\fP(7) ,
\fBSAPHanaSR-showAttr\fP(8) , \fBSAPHanaSR_maintenance_examples\fP(7) ,
\fBSAPHanaSR.py\fP(7) , \fBSAPHanaSrMultiTarget.py\fP(7) ,
\fBcrm_simulate\fP(8) , \fBcibadmin\fP(8) , \fBcrm_mon\fP(8) ,
\fBcs_convert_time\fP(8) , \fBcs_clusterstate\fP(8) , \fBcs_show_hana_info\fP(8)
.br
https://documentation.suse.com/sbp/all/?context=sles-sap ,
.br
https://documentation.suse.com/sles-sap/ ,
.br
https://www.susecon.com/archive-2020.html
.\"
.SH AUTHORS
A.Briel, F.Herschel, L.Pinne
.\"
.SH COPYRIGHT
(c) 2021 SUSE LLC
.br
SAPHanaSR-manageAttr comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"
