.\" Version: 0.180.0
.\"
.TH SAPHanaSR-migrate 8 "12 Mar 2021" "" "SAPHanaSR-ScaleOut"
.\"
.SH NAME
SAPHanaSR-migrate \- Helps with migrating Linux cluster attributes for SAP HANA system replication.
.\"
.SH SYNOPSYS
\fBSAPHanaSR-migrate\fR [ --help | --version ]
.br
\fBSAPHanaSR-migrate\fR [ TODO ]
.\"
.SH DESCRIPTION
SAPHanaSR-migrate \- Helps with migrating Linux cluster attributes for SAP HANA system replication.

TODO
.\"
.SH RETURN CODES
.B 0
Successful program execution.
.br
.B >0
Usage, syntax or execution errors.
.\"
.SH EXAMPLES
.TP
# SAPHanaSR-migrate TODO
.\"
.SH FILES
.TP
/usr/bin/SAPHanaSR-showAttr
        the program itself.
.TP
/usr/lib/SAPHanaSR-ScaleOut/SAPHanaSRTools.pm
        needed functions.
.\"
.SH BUGS
Feedback is welcome, please mail to feedback@suse.com.
.\"
.\"
.SH SEE ALSO
\fBocf_suse_SAPHanaController\fP(7) , \fBocf_suse_SAPHanaTopology\fP(7) ,
\fBSAPHanaSR-ScaleOut\fP(7) , \fBSAPHanaSR-showAttr\fP(8) ,
\fBSAPHanaSR_maintenance_examples\fP(7) ,
\fBcrm_simulate\fP(8) , \fBcibadmin\fP(8) , \fBcrm_mon\fP(8) ,
\fBcs_convert_time\fP(8) , \fBcs_clusterstate\fP(8) , \fBcs_show_hana_info\fP(8)
.br
https://documentation.suse.com/sbp/all/?context=sles-sap ,
.br
https://documentation.suse.com/sles-sap/ ,
.br
https://www.susecon.com/doc/2015/sessions/TUT19921.pdf ,
.br
https://www.susecon.com/doc/2016/sessions/TUT90846.pdf ,
.br
https://www.susecon.com/archive-2020.html
.\"
.SH AUTHORS
A.Briel, F.Herschel, L.Pinne
.\"
.SH COPYRIGHT
(c) 2021 SUSE LLC
.br
SAPHanaSR-migrate comes with ABSOLUTELY NO WARRANTY.
.br
For details see the GNU General Public License at
http://www.gnu.org/licenses/gpl.html
.\"



