#!/usr/bin/perl
#
# get_all_lnx_attributes
#
# license: GPL
# author:  fabian.herschel@suse.com
# date:    2015-04-14
my $Version="0.4.2015.04.14.1";
# 
#
use POSIX;
use strict;
use Getopt::Long;
#use lib '/usr/lib/SAPHanaSR-ScaleOut';
#use SAPHanaSRTools;

my $sid="";
my $ino="";
my $sortBy="";
my $table_titleH = "Host";
#my %Name;
my %Host;
my %Site;
my %Global;
my %HName;
my %SName;
my %GName;
my $help;
my $version;

	my $result = GetOptions ("sid=s" => \$sid,
	                      "ino=s" => \$ino,
	                      "sort=s" => \$sortBy,
                          "version" => \$version,
                          "help" => \$help,
		 );


if ( $help ) {
   printf "Nice try\n";
   exit 0;
}
if ( $version ) {
   printf "%s\n", $Version;
   exit 0;
}

sub max { # thanks to http://www.perlunity.de/perl/forum/thread_018329.shtml
 my $a = shift;
 my $b = shift;
 return $a > $b ? $a : $b;
}

#sub print_attr_host()
#{
#    my ($HKey, $AKey);
#	printf "%-22s", "Attribute \\ Host";
#	foreach $HKey (sort keys %Host) {
#	   printf "%-16s ", $HKey;
#	}
#	printf "\n";
#
#	printf "%s\n", "-" x 120 ;
#
#	foreach $AKey (sort keys %Name) {
#	   printf "%-22s", $AKey;
#	   foreach $HKey (sort keys %Host) {
#		   printf "%-16.16s ", $Host{$HKey} -> {$AKey};
#		}
#
#	   printf "\n";
#	}
#	return 0;
#}

sub print_host_attr($$$$)
{
    my ($refH, $refN, $title, $sort) = @_;
    my ($AKey, $HKey, $len, $line_len, $hclen);
    $hclen=$$refN{_hosts}->{_length};
    $line_len=$hclen+1;
    printf "%-$hclen.${hclen}s ", "$title";
    #
    # headline
    #
    foreach $AKey (sort keys %$refN) {
        if ($AKey ne "_hosts") {
            $len = $$refN{$AKey}->{_length};
            $line_len=$line_len+$len+1;
            
            if ( $AKey eq $sort ) {
               printf "*%-$len.${len}s ", $$refN{$AKey}->{_title};
            } else {
               printf "%-$len.${len}s ", "$$refN{$AKey}->{_title}";
            }
        }
    }
    printf "\n";
    printf "%s\n", "-" x $line_len ;
    #
    # object / name / value lines
    #
    if ( $sort eq "" ) {
        foreach $HKey (sort keys %$refH) {
            printf "%-$hclen.${hclen}s ", $HKey;
            foreach $AKey (sort keys %$refN) {
                if ($AKey ne "_hosts") {
                    $len = $$refN{$AKey}->{_length};
                    printf "%-$len.${len}s ", $$refH{$HKey} -> {$AKey};
                }
            }
            printf "\n";
        }    
    } else {
       # try to sort by site (other attrs to follow)
       # first try to get a ordered list of attribute values assigned host names
       my $sortV;
       my %GroupedHosts;
       foreach $HKey (sort keys %$refH) {
           $sortV = $$refH{$HKey} -> {$sort};
           push(@{$GroupedHosts{$sortV}}, $HKey);
           #printf "TST: <%s>\n", $sortV;
       }
       # not ready so far only print the grouped hosts
       foreach $sortV (sort keys %GroupedHosts) {
           #my $StrHosts;
           #$StrHosts=join(":", @{$GroupedHosts{$sortV}});
           my $Host;
           foreach $Host (@{$GroupedHosts{$sortV}}) {
               printf "%-$hclen.${hclen}s ", $Host;
               foreach $AKey (sort keys %$refN) {
                if ($AKey ne "_hosts") {
                    $len = $$refN{$AKey}->{_length};
                    printf "%-$len.${len}s ", $$refH{$Host} -> {$AKey};
                }
            }
            printf "\n";
           }
           #printf "TST: <%s> -> <%s>\n", $sortV, $StrHosts;
       }
    }
    printf "\n";
    return 0;
}

open ListInstances, "/usr/sap/hostctrl/exe/saphostctrl -function ListInstances|";
while (<ListInstances>) {
   # try to catch:  Inst Info : LNX - 42 - lv9041 - 740, patch 36, changelist 1444691
   chomp;
   if ( $_ =~ /:\s+([A-Z][A-Z0-9][A-Z0-9])\s+-/ ) {
      $sid=tolower("$1");
   }
}
close ListInstances;

sub insertAttribute($$$$$) { 
    my ($refHash, $refN, $object, $attribute, $value) = @_;
    my $table_titleH="";
    if ( $attribute =~ /hana_${sid}_(.*)/ ) {
       $attribute =  $1;
    }
       #
       # handle the hosts name and table-title
       #
       $$refHash{$object}->{$attribute}=${value};
       if ( defined ($$refN{_hosts}->{_length})) {
          $$refN{_hosts}->{_length} = max($$refN{_hosts}->{_length}, length($object ));
       } else {
          $$refN{_hosts}->{_length} = length($object );
       }
       $$refN{_hosts}->{_length} = max($$refN{_hosts}->{_length}, length( $table_titleH));
       #
       # now handle the attributes name and value
       #
       $$refN{$attribute}->{$object}=${value};
       $$refN{$attribute}->{$object}=${value};
       if ( defined ($$refN{$attribute}->{_length})) {
          $$refN{$attribute}->{_length} = max($$refN{$attribute}->{_length}, length($value ));
       } else {
          $$refN{$attribute}->{_length} = length($value );
       }
       $$refN{$attribute}->{_title} = $attribute; 
       $$refN{$attribute}->{_length} = max($$refN{$attribute}->{_length}, length( $$refN{$attribute}->{_title}));
       # printf "%-8s %-20s %-30s\n", $1, $2, $3;
}

open CIB, "cibadmin -Ql |";
while (<CIB>) {
   chomp;
   my ($host, $name, $site, $value);
   if ( $_ =~ /nvpair.*name="([a-zA-Z0-9\_\-]+_${sid}_([a-zA-Z0-9\-\_]+))"/ ) {
      $name=$1;
      if ( $_ =~ /id=.(status|nodes)-([a-zA-Z0-9\_\-]+)-/ ) {
         # found attribute in nodes forever and reboot store
         $host=$2;
         if ( $_ =~ /value="([^"]+)"/ ) {
             $value=$1;
             insertAttribute(\%Host, \%HName, $host, $name, $value);
         }
      } elsif ( $_ =~ /id=.SAPHanaSR-[a-zA-Z0-9\_\-]+_site_[a-zA-Z0-9\-]+_([a-zA-Z0-9\_\-]+)/) {
         # found a site attribute
         $site=$1;
         if ( $name =~ /[a-zA-Z0-9\_\-]+_site_([a-zA-Z0-9\-]+)/ ) {
            $name = $1;
         }
         if ( $_ =~ /value="([^"]+)"/ ) {
             $value=$1;
             insertAttribute(\%Site, \%SName, $site, $name, $value);
         }
      } elsif ( $_ =~ /id=.SAPHanaSR-[a-zA-Z0-9\_\-]+_glob_[a-zA-Z0-9\_\-]+/) {
         # found a global attribute
         $host="GLOBAL";
         if ( $name =~ /([a-zA-Z0-9\_\-]+)_glob_([a-zA-Z0-9\_\-]+)/ ) {
            $name = $2;
         }
         if ( $_ =~ /value="([^"]+)"/ ) {
             $value=$1;
             insertAttribute(\%Global, \%GName, "global", $name, $value);
         }
      }
   }
}
close CIB;

#print_attr_host;
print_host_attr(\%Global, \%GName, "Global", "");
print_host_attr(\%Site,   \%SName, "Sites",  "");
#print_host_attr(\%Host,   \%HName, "Hosts",  "site");
print_host_attr(\%Host,   \%HName, "Hosts",  $sortBy);
